// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pffxmqtvqwvyuxkougxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmZnhtcXR2cXd2eXV4a291Z3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDE3ODMsImV4cCI6MjA2MTUxNzc4M30.KJuUowizeRWR7aFWLBSPRVB_oqdncJ37zUysfQbNcSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);